version: '3'
services:
  node:
    container_name: txrx-redis-p2p-node
    image: txrx/redis-p2p-node:devel
    user: "${UID}:${GID}"
    build:
      context: .
      args:
        GIT_NAME: ${GIT_NAME}
        GIT_EMAIL: ${GIT_EMAIL}
    volumes:
      - ./:/usr/src/app
      - ~/.npmrc:/home/node/.npmrc
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    env_file:
      - .env
